/*
 * University of Louisville
 * Spring 2014 - CECS 622
 * Project Title: Car Wash Queuing Model Simulation
 * Author: Phi Bui
 */

package carwashmodel;
import carwashmodel.Class.MultiServerMultiQueueSystem;
import carwashmodel.Class.MultiServerSingleQueueSystem;
import carwashmodel.Class.SingleJobServerSystem;
import java.awt.event.KeyEvent;

/**
 *
 * @author Phi Bui
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnSingleServerRun = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMultiServerSingleRun = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tbCase2TotalServer = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnMultiServerMultiRun = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tbCase3TotalServer = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tbInterArrivalMin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbTotalRunningTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbServeMu = new javax.swing.JTextField();
        tbInterArrivalMax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbServeSigma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CECS 622 - Car Wash Queuing Model Simulator - Phi Bui");
        setResizable(false);

        txtResults.setEditable(false);
        txtResults.setColumns(20);
        txtResults.setRows(5);
        jScrollPane1.setViewportView(txtResults);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Case 1: Single-Sever Queuing Model"));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 100));

        btnSingleServerRun.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSingleServerRun.setText("Run Simulation");
        btnSingleServerRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingleServerRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnSingleServerRun)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSingleServerRun, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Case 2: Multi-Server Single Queuing Model"));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 100));

        btnMultiServerSingleRun.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMultiServerSingleRun.setText("Run Simulation");
        btnMultiServerSingleRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiServerSingleRunActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Server");

        tbCase2TotalServer.setText("2");
        tbCase2TotalServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbCase2TotalServerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMultiServerSingleRun)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbCase2TotalServer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tbCase2TotalServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMultiServerSingleRun)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Case 3: Multi-Server Multi Queuing Model"));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 100));

        btnMultiServerMultiRun.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMultiServerMultiRun.setText("Run Simulation");
        btnMultiServerMultiRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiServerMultiRunActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Server");

        tbCase3TotalServer.setText("2");
        tbCase3TotalServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbCase3TotalServerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMultiServerMultiRun)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbCase3TotalServer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tbCase3TotalServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMultiServerMultiRun)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerneral Settings"));

        tbInterArrivalMin.setText("3");
        tbInterArrivalMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbInterArrivalMinKeyTyped(evt);
            }
        });

        jLabel2.setText("Interarrival Min");

        tbTotalRunningTime.setText("50");
        tbTotalRunningTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbTotalRunningTimeKeyTyped(evt);
            }
        });

        jLabel5.setText("Service SIGMA");

        tbServeMu.setText("5");
        tbServeMu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbServeMuKeyTyped(evt);
            }
        });

        tbInterArrivalMax.setText("10");
        tbInterArrivalMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbInterArrivalMaxKeyTyped(evt);
            }
        });

        jLabel3.setText("Interarrival Max");

        tbServeSigma.setText("1");
        tbServeSigma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbServeSigmaKeyTyped(evt);
            }
        });

        jLabel1.setText("Total Running Time");

        jLabel4.setText("Service MU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbTotalRunningTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(tbInterArrivalMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbInterArrivalMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbServeMu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbServeSigma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tbTotalRunningTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(tbServeSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbInterArrivalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(tbInterArrivalMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbServeMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setText("Reset Settings");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSingleServerRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingleServerRunActionPerformed

        int totalRunningTime = Integer.parseInt(tbTotalRunningTime.getText());
        int interArrivalMin = Integer.parseInt(tbInterArrivalMin.getText());
        int interArrivalMax = Integer.parseInt(tbInterArrivalMax.getText());
        int serveMu = Integer.parseInt(tbServeMu.getText());
        int serveSigma = Integer.parseInt(tbServeSigma.getText());

        SingleJobServerSystem sys = new SingleJobServerSystem();
        sys.SetTotalRunningTime(totalRunningTime);
        sys.SetInterArrivalMin(interArrivalMin);
        sys.SetInterArrivalMax(interArrivalMax);
        sys.SetServeMu(serveMu);
        sys.SetServeSigma(serveSigma);
        sys.runner.Run();

        txtResults.setText(sys.strPrintResults.toString());
    }//GEN-LAST:event_btnSingleServerRunActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        tbTotalRunningTime.setText("50"); //Set Total Running Time. 50 by default
        tbServeSigma.setText("1"); //Set Serve Sigma. 1 by default
        tbServeMu.setText("5"); //Set Serve Mu. 5 by default
        tbInterArrivalMin.setText("3"); //Set Inter-Arrival Min. 3 by default
        tbInterArrivalMax.setText("10"); //Set Inter-Arrival Max. 10 by default
        tbCase2TotalServer.setText("2"); //Set Total number of servers. 2 by default
        tbCase3TotalServer.setText("2"); //Set Total number of servers. 2 by default
        txtResults.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tbTotalRunningTimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbTotalRunningTimeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tbTotalRunningTimeKeyTyped

    private void tbInterArrivalMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbInterArrivalMinKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tbInterArrivalMinKeyTyped

    private void tbInterArrivalMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbInterArrivalMaxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tbInterArrivalMaxKeyTyped

    private void tbServeMuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbServeMuKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tbServeMuKeyTyped

    private void tbServeSigmaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbServeSigmaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tbServeSigmaKeyTyped

    private void tbCase2TotalServerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCase2TotalServerKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tbCase2TotalServerKeyTyped

    private void tbCase3TotalServerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCase3TotalServerKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tbCase3TotalServerKeyTyped

    private void btnMultiServerSingleRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiServerSingleRunActionPerformed

        int totalRunningTime = Integer.parseInt(tbTotalRunningTime.getText());
        int interArrivalMin = Integer.parseInt(tbInterArrivalMin.getText());
        int interArrivalMax = Integer.parseInt(tbInterArrivalMax.getText());
        int serveMu = Integer.parseInt(tbServeMu.getText());
        int serveSigma = Integer.parseInt(tbServeSigma.getText());
        int totalServer = Integer.parseInt(tbCase2TotalServer.getText());

        MultiServerSingleQueueSystem multiServer = new MultiServerSingleQueueSystem(totalRunningTime, interArrivalMin, interArrivalMax, serveMu, serveSigma, totalServer);
        multiServer.runner.Run();

        txtResults.setText(multiServer.strPrintResults.toString());
    }//GEN-LAST:event_btnMultiServerSingleRunActionPerformed

    private void btnMultiServerMultiRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiServerMultiRunActionPerformed

        int totalRunningTime = Integer.parseInt(tbTotalRunningTime.getText());
        int interArrivalMin = Integer.parseInt(tbInterArrivalMin.getText());
        int interArrivalMax = Integer.parseInt(tbInterArrivalMax.getText());
        int serveMu = Integer.parseInt(tbServeMu.getText());
        int serveSigma = Integer.parseInt(tbServeSigma.getText());
        int totalServer = Integer.parseInt(tbCase3TotalServer.getText());

        MultiServerMultiQueueSystem multiServerMultiQueue = new MultiServerMultiQueueSystem(totalRunningTime, interArrivalMin, interArrivalMax, serveMu, serveSigma, totalServer);
        multiServerMultiQueue.runner.Run();

        txtResults.setText(multiServerMultiQueue.strPrintResults.toString());
    }//GEN-LAST:event_btnMultiServerMultiRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMultiServerMultiRun;
    private javax.swing.JButton btnMultiServerSingleRun;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSingleServerRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbCase2TotalServer;
    private javax.swing.JTextField tbCase3TotalServer;
    private javax.swing.JTextField tbInterArrivalMax;
    private javax.swing.JTextField tbInterArrivalMin;
    private javax.swing.JTextField tbServeMu;
    private javax.swing.JTextField tbServeSigma;
    private javax.swing.JTextField tbTotalRunningTime;
    public javax.swing.JTextArea txtResults;
    // End of variables declaration//GEN-END:variables
}
